"""
Django settings for vexora project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

print(GROQ_API_KEY)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cd(or%ouqonoh+4-4eu3hty1fli=a9r3$*#dr+ofe#fvv)8iu0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vexora',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'vexora.middleware.subscription_middleware.SubscriptionMiddleware',# Middleware personalizado para verificar suscripción
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "Templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vexora.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'prueba',       # Nombre de tu base de datos
        'USER': 'root',               # Usuario de MySQL
        'PASSWORD': '',       # Contraseña de MySQL
        'HOST': 'localhost',               # o la IP del servidor MySQL
        'PORT': '3306',                    # Puerto por defecto de MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES',  time_zone = '-06:00'"
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


STATIC_URL = 'static/'
# Carpeta global de archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# OpenAI assistant settings
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = 'gpt-3.5-turbo'


AUTH_USER_MODEL = "vexora.CustomUser"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = 'vexora:login'  # a dónde ir si no está logueado
LOGIN_REDIRECT_URL = '/users/'
LOGOUT_REDIRECT_URL = reverse_lazy('vexora:login')  # a dónde ir después de cerrar sesión
LANGUAGE_CODE = "es"
TIME_ZONE = "America/Mexico_City"
QUILL_CONFIGS = {
    'default': {
        'theme': 'snow',
        'modules': {
            'syntax': True,
            'toolbar': [
                ['bold', 'italic', 'underline', 'strike'],  # toggled buttons
                ['blockquote', 'code-block','link'],

                [{'header': 1}, {'header': 2},{'header':3}],  # custom button values
                [{'list': 'ordered'}, {'list': 'bullet'}],
                [{'script': 'sub'}, {'script': 'super'}],  # superscript/subscript
                [{'indent': '-1'}, {'indent': '+1'}],  # outdent/indent
                [{'direction': 'rtl'}],  # text direction

                [{'size': ['small', False, 'large', 'huge']}],  # custom dropdown
                [{'header': [1, 2, 3, 4, 5, 6, False]}],

                [{'color': []}, {'background': []}],  # dropdown with defaults from theme
                [{'font': []}],
                [{'align': []}],

                ['clean'],  # remove formatting button

                ['link', 'image', 'video']  # link and image, video
            ]
        }
    }
}# settings.py
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'tucorreo@gmail.com'

EMAIL_HOST_PASSWORD = 'apppassword'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ==========================================
# CONFIGURACIÓN DE CORREO GMAIL
# ==========================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 465
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = os.environ.get(
    "VEXORA_EMAIL_USER",
    ""
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "VEXORA_EMAIL_PASSWORD",
    ""
)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_TIMEOUT = 10
