# Generated by Django 5.2 on 2026-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vexora", "0001_initial"),
    ]

    operations = [
        # Estas columnas y cambios ya existen físicamente
        # en MySQL. Solo se registran en el estado de Django.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="cart",
                    unique_together=set(),
                ),

                migrations.AlterUniqueTogether(
                    name="cartitem",
                    unique_together=set(),
                ),

                migrations.AlterUniqueTogether(
                    name="product",
                    unique_together=set(),
                ),

                migrations.AddField(
                    model_name="cartitem",
                    name="updated_at",
                    field=models.DateTimeField(
                        auto_now=True,
                    ),
                ),

                migrations.AddField(
                    model_name="product",
                    name="reserved_stock",
                    field=models.PositiveIntegerField(
                        default=0,
                        verbose_name="Stock reservado",
                    ),
                ),

                migrations.AddField(
                    model_name="productvariant",
                    name="reserved_stock",
                    field=models.PositiveIntegerField(
                        default=0,
                        verbose_name="Stock reservado",
                    ),
                ),
            ],
        ),

        # Estos cambios todavía sí deben ejecutarse
        # en la base de datos.
        migrations.AlterField(
            model_name="product",
            name="min_stock",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="Minimum stock",
            ),
        ),

        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="Stock",
            ),
        ),

        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("company", "user"),
                name="unique_cart_per_company_user",
            ),
        ),

        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "variant"),
                name="unique_product_variant_per_cart",
            ),
        ),

        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    quantity__gte=1,
                ),
                name="cart_item_quantity_gte_one",
            ),
        ),

        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("company", "item_number"),
                name="unique_product_number_per_company",
            ),
        ),

        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    stock__gte=0,
                ),
                name="product_stock_non_negative",
            ),
        ),

        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    reserved_stock__gte=0,
                ),
                name="product_reserved_stock_non_negative",
            ),
        ),

        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    reserved_stock__lte=models.F("stock"),
                ),
                name="product_reserved_stock_lte_stock",
            ),
        ),

        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    stock__gte=0,
                ),
                name="variant_stock_non_negative",
            ),
        ),

        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    reserved_stock__gte=0,
                ),
                name="variant_reserved_stock_non_negative",
            ),
        ),

        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    reserved_stock__lte=models.F("stock"),
                ),
                name="variant_reserved_stock_lte_stock",
            ),
        ),
    ]