# Generated by Django 5.2 on 2026-05-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('secondary_color', models.CharField(default='#1E293B', max_length=7)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
