# Generated by Django 5.2.16 on 2026-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
    ]
