# Generated by Django 5.2 on 2026-05-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='background_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='card_background',
            field=models.CharField(default='#1e293b', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
