# Generated by Django 5.2 on 2026-07-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0002_company_is_active_company_logo_company_rfc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['item_number'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.PositiveIntegerField(default=0, help_text='Número secuencial del producto para esta compañía', verbose_name='Número de producto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='members', to='vexora.company'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'item_number')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'item_number'], name='vexora_prod_company_216c75_idx'),
        ),
    ]
