# Generated by Django 5.2 on 2026-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0002_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='campo_pureba_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
