# Generated by Django 5.2 on 2026-07-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0003_customuser_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='members', to='vexora.company'),
        ),
    ]
