# Generated by Django 5.2 on 2026-07-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0002_alter_cart_unique_together_and_more'),
        ('vexora', '0002_fix_missing_is_client'),
        ('vexora', '0004_alter_customuser_companies'),
    ]

    operations = [
    ]
