# Generated by Django 5.2 on 2026-06-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0004_create_customuser_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.AddField(
            model_name='plan',
            name='groups_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_collaborators',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_groups',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_providers',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='providers_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='sales_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='users_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_type',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_branches',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_products',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
