# Generated by Django 5.2 on 2026-07-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0005_merge_20260721_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_repost',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='report_module',
            field=models.BooleanField(default=False),
        ),
    ]
