# Generated by Django 5.2 on 2026-05-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0005_customuser_company_subscription_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
