# Generated by Django 5.2 on 2026-07-02 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0005_remove_plan_created_at_plan_groups_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='vexora.company'),
        ),
    ]
