# Generated by Django 5.2 on 2026-05-18 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0006_siteconfiguration_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_type',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='custom_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_branches',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
