# Generated by Django 5.2 on 2026-07-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0006_alter_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='company',
        ),
    ]
