# Generated by Django 5.2 on 2026-07-02 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0008_alter_customuser_groups_role_customuser_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
    ]
