# Generated by Django 6.0.5 on 2026-07-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0009_remove_customuser_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['item_number'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.PositiveIntegerField(default=0, help_text='Número secuencial del producto para esta compañía', verbose_name='Número de producto'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'item_number')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'item_number'], name='vexora_prod_company_216c75_idx'),
        ),
    ]
