# Generated by Django 5.2 on 2026-05-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0010_alter_company_name_smtpconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfiguration',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
