# Generated by Django 5.2 on 2026-07-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vexora', '0003_alter_category_options_alter_product_options_and_more'),
        ('vexora', '0003_cart_cartitem'),
    ]

    operations = [
    ]
